# Generated by Django 4.2.11 on 2024-03-13 08:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0002_alter_assetlog_checkout_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetlog',
            name='return_date',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
